In [235]:
import pandas as pd
import numpy as np
from geopy.distance import geodesic

In [ ]:
geodesic()

geopy.distance.geodesic

In [148]:
pas = pd.read_csv("data/PASAJEROS_ARANJUEZ_SANTA_CRUZ.csv")
pas.columns = pas.columns.str.lower()

In [268]:
tra = pd.read_csv("data/TRANSPORTES_ARANJUEZ_SANTA_CRUZ.csv", encoding="latin-1", sep=";")
tra.columns = tra.columns.str.lower()

In [269]:
# Atributo esarchivolinea, puede ser interesante

columnas_drop = ["nombrearchivo", "idempresa", "idpersona", "esarchivolinea", "diferenciadepasajeros", "ordenregistro",
       "tipocarga", "idpersonausuario", "archivofirmado","fechavencimientofirma", "indfechacreacion", "fecha_carga",
       "ultimoestadopuertas", "presentocambioenpuertas", "ordenregistro","ipmaquina", "placavehiculo", "codigo_id",
       "id_tipo_ruta", "nombre_ruta", "secuenciarecorrido", "cantidadregistros", "ultimafecharegistro"]

tra = tra.drop(columnas_drop, axis=1)

In [270]:
tra["ultimalatitudregistro"] = pd.to_numeric(tra["ultimalatitudregistro"].str.replace(",", "."))
tra["ultimalongitudregistro"] = pd.to_numeric(tra["ultimalongitudregistro"].str.replace(",", "."))

In [274]:
tra.head()

,empresa_transporte,idvehiculo,idruta,codigo_ruta,min_registros_ruta,longitudruta,tipo_ruta,fechainiciodespacho,fechafindespacho,recorridofinalizado,fecha_creacion,cantpasajerossuben,cantpasajerosbajan,ultimalongitudregistro,ultimalatitudregistro,distanciarecorrido,recorridoincumplido,distanciaincumplidainicio,distanciaincumplidafin
0,TRANSPORTES ARANJUEZ SANTA CRUZ,2595,803,024,33,"8026,96",Directa no centro,23/09/25 21:55:09,23/09/25 22:54:16,N,23/09/2025 21:55:09,0,0,-75.564079,6.288920,3131,S,"2289,21","182,73"
1,TRANSPORTES ARANJUEZ SANTA CRUZ,5265,803,024,33,"8026,96",Directa no centro,23/09/25 21:41:04,23/09/25 21:55:55,S,23/09/2025 21:41:04,1,14,-75.562950,6.290425,3141,S,"2085,51","192,06"
2,TRANSPORTES ARANJUEZ SANTA CRUZ,5268,529,041 D,70,"16776,67",Directa centro,23/09/25 21:40:31,23/09/25 22:47:11,S,23/09/2025 21:40:31,4,3,-75.551727,6.287636,13179,S,"216,73","480,45"
3,TRANSPORTES ARANJUEZ SANTA CRUZ,5222,529,041 D,70,"16776,67",Directa centro,23/09/25 21:20:32,23/09/25 22:32:46,S,23/09/2025 21:20:32,4,3,-75.552109,6.287522,13399,S,"254,01","454,19"
4,TRANSPORTES ARANJUEZ SANTA CRUZ,5271,803,024,33,"8026,96",Directa no centro,23/09/25 21:12:57,23/09/25 21:30:28,S,23/09/2025 21:12:57,4,19,-75.564247,6.288287,3332,S,"2350,1","124,81"

In [275]:
tra.groupby(["idruta", "idvehiculo"]).get_group((525,6892)).sort_values(by=["ultimalongitudregistro","ultimalongitudregistro"])

,empresa_transporte,idvehiculo,idruta,codigo_ruta,min_registros_ruta,longitudruta,tipo_ruta,fechainiciodespacho,fechafindespacho,recorridofinalizado,fecha_creacion,cantpasajerossuben,cantpasajerosbajan,ultimalongitudregistro,ultimalatitudregistro,distanciarecorrido,recorridoincumplido,distanciaincumplidainicio,distanciaincumplidafin
1642,TRANSPORTES ARANJUEZ SANTA CRUZ,6892,525,022,69,"16621,12",Directa centro,21/09/25 15:05:57,21/09/25 16:37:35,S,21/09/2025 15:05:57,18,23,-75.549805,6.291781,16900,S,"70,64","184,76"
1892,TRANSPORTES ARANJUEZ SANTA CRUZ,6892,525,022,69,"16621,12",Directa centro,21/09/25 06:03:36,21/09/25 07:12:30,S,21/09/2025 06:03:36,11,13,-75.549767,6.291602,16459,S,89,"200,71"
1927,TRANSPORTES ARANJUEZ SANTA CRUZ,6892,525,022,69,"16621,12",Directa centro,21/09/25 04:37:31,21/09/25 05:52:00,S,21/09/2025 04:37:31,8,8,-75.549599,6.292368,16630,S,0,"188,77"
1743,TRANSPORTES ARANJUEZ SANTA CRUZ,6892,525,022,69,"16621,12",Directa centro,21/09/25 11:20:32,21/09/25 12:45:17,S,21/09/2025 11:20:32,13,11,-75.549553,6.291378,16805,S,"112,73",0
1788,TRANSPORTES ARANJUEZ SANTA CRUZ,6892,525,022,69,"16621,12",Directa centro,21/09/25 09:35:31,21/09/25 10:58:16,S,21/09/2025 09:35:31,8,7,-75.549171,6.291325,16638,S,"128,63","53,34"
1689,TRANSPORTES ARANJUEZ SANTA CRUZ,6892,525,022,69,"16621,12",Directa centro,21/09/25 13:20:32,21/09/25 14:39:42,S,21/09/2025 13:20:32,22,21,-75.548065,6.291183,16618,S,"218,75","181,15"
1839,TRANSPORTES ARANJUEZ SANTA CRUZ,6892,525,022,69,"16621,12",Directa centro,21/09/25 07:50:02,21/09/25 09:03:02,S,21/09/2025 07:50:02,6,6,-75.547546,6.291081,16435,S,"272,33",0

In [ ]:
columnas_drop = ["unnamed: 0", "empresa", "nombrearchivo"]
pas = pas.drop(columnas_drop, axis=1)

In [117]:
pas.head()

,codigoruta,rutaot,descripcion,fecha,horaregistro,longitud,latitud,velocidad,passuben,pasbajan,consecutivo
0,121275,041 I,ARANJUEZ GUADALUPE,22/09/2025,06:33:39,"-75,546005","6,286640",17,1,0,9
1,121275,041 I,ARANJUEZ GUADALUPE,22/09/2025,06:34:01,"-75,545937","6,287443",14,1,0,11
2,121275,041 I,ARANJUEZ GUADALUPE,22/09/2025,06:34:31,"-75,545860","6,287635",0,4,0,13
3,121275,041 I,ARANJUEZ GUADALUPE,22/09/2025,06:34:52,"-75,546577","6,287738",17,1,0,14
4,121275,041 I,ARANJUEZ GUADALUPE,22/09/2025,06:35:15,"-75,546684","6,287658",6,2,0,16

In [126]:
pas.groupby(["codigoruta"], sort=True).head().sort_values(by="consecutivo")

,codigoruta,rutaot,descripcion,fecha,horaregistro,longitud,latitud,velocidad,passuben,pasbajan,consecutivo
16231,111255,024,PLAYÓN DE LOS COMUNEROS - ORIENTAL,22/09/2025,05:27:18,"-75,548798","6,302617",4,1,0,1
329,121265,041 D,ARANJUEZ ANILLO,23/09/2025,06:13:44,"-75,552742","6,287153",6,2,0,4
629,111225,022,SANTA CRUZ - TERMINAL,22/09/2025,04:11:20,"-75,547676","6,291083",0,1,0,6
330,121265,041 D,ARANJUEZ ANILLO,23/09/2025,06:14:03,"-75,552689","6,286893",8,1,0,6
630,111225,022,SANTA CRUZ - TERMINAL,22/09/2025,04:11:52,"-75,547676","6,291083",0,1,0,7
16232,111255,024,PLAYÓN DE LOS COMUNEROS - ORIENTAL,22/09/2025,05:29:44,"-75,549454","6,303542",0,2,0,8
16217,111245,024,PLAYÓN DE LOS COMUNEROS,22/09/2025,03:47:18,"-75,548653","6,302780",6,2,0,8
16233,111255,024,PLAYÓN DE LOS COMUNEROS - ORIENTAL,22/09/2025,05:29:58,"-75,549454","6,303542",0,1,0,9
0,121275,041 I,ARANJUEZ GUADALUPE,22/09/2025,06:33:39,"-75,546005","6,286640",17,1,0,9
1616,111285,042,ARANJUEZ INTERMEDIA,21/09/2025,04:51:23,"-75,546021","6,286435",7,2,0,10
16218,111245,024,PLAYÓN DE LOS COMUNEROS,22/09/2025,03:47:36,"-75,548546","6,302930",5,1,0,10
1,121275,041 I,ARANJUEZ GUADALUPE,22/09/2025,06:34:01,"-75,545937","6,287443",14,1,0,11
4550,111235,023,POPULAR N° 1,21/09/2025,04:56:00,"-75,551636","6,305412",0,1,0,13
2,121275,041 I,ARANJUEZ GUADALUPE,22/09/2025,06:34:31,"-75,545860","6,287635",0,4,0,13
3,121275,041 I,ARANJUEZ GUADALUPE,22/09/2025,06:34:52,"-75,546577","6,287738",17,1,0,14
16219,111245,024,PLAYÓN DE LOS COMUNEROS,22/09/2025,03:48:59,"-75,549583","6,303545",3,2,0,14
16220,111245,024,PLAYÓN DE LOS COMUNEROS,22/09/2025,03:49:21,"-75,549576","6,303627",11,1,0,16
4,121275,041 I,ARANJUEZ GUADALUPE,22/09/2025,06:35:15,"-75,546684","6,287658",6,2,0,16
1617,111285,042,ARANJUEZ INTERMEDIA,21/09/2025,04:54:00,"-75,547127","6,286948",14,1,0,18
331,121265,041 D,ARANJUEZ ANILLO,23/09/2025,06:19:40,"-75,553741","6,282577",7,1,0,20
1618,111285,042,ARANJUEZ INTERMEDIA,21/09/2025,04:54:47,"-75,547714","6,287053",8,1,0,20
16234,111255,024,PLAYÓN DE LOS COMUNEROS - ORIENTAL,22/09/2025,05:32:27,"-75,552689","6,304487",0,1,0,21
16235,111255,024,PLAYÓN DE LOS COMUNEROS - ORIENTAL,22/09/2025,05:32:48,"-75,553040","6,304735",0,1,0,23
332,121265,041 D,ARANJUEZ ANILLO,23/09/2025,06:20:56,"-75,555603","6,282245",8,2,0,23
1619,111285,042,ARANJUEZ INTERMEDIA,21/09/2025,04:56:07,"-75,549751","6,287218",4,1,0,24
631,111225,022,SANTA CRUZ - TERMINAL,22/09/2025,04:20:36,"-75,554642","6,291317",15,1,0,28
4551,111235,023,POPULAR N° 1,21/09/2025,05:03:15,"-75,548790","6,302562",0,4,0,29
1620,111285,042,ARANJUEZ INTERMEDIA,21/09/2025,04:59:11,"-75,550117","6,281690",12,1,0,31
7295,113136,024,024-BARRIAL,22/09/2025,17:29:54,"-75,572853","6,280620",2,0,1,31
632,111225,022,SANTA CRUZ - TERMINAL,22/09/2025,04:22:41,"-75,555885","6,287615",24,1,0,32
333,121265,041 D,ARANJUEZ ANILLO,23/09/2025,06:23:50,"-75,557259","6,285800",13,1,0,32
4552,111235,023,POPULAR N° 1,21/09/2025,05:05:07,"-75,548615","6,302122",3,1,0,33
7296,113136,024,024-BARRIAL,22/09/2025,17:31:16,"-75,573242","6,279625",0,0,1,34
633,111225,022,SANTA CRUZ - TERMINAL,22/09/2025,04:23:07,"-75,556183","6,287107",16,1,0,35
7297,113136,024,024-BARRIAL,22/09/2025,17:31:47,"-75,573235","6,279627",0,0,16,35
7298,113136,024,024-BARRIAL,22/09/2025,17:32:18,"-75,573235","6,279627",0,0,8,36
4553,111235,023,POPULAR N° 1,21/09/2025,05:06:12,"-75,549240","6,299580",0,1,0,37
4554,111235,023,POPULAR N° 1,21/09/2025,05:06:25,"-75,549446","6,299242",0,1,0,38
16221,111245,024,PLAYÓN DE LOS COMUNEROS,22/09/2025,03:56:00,"-75,555550","6,306992",16,1,0,45
7299,113136,024,024-BARRIAL,22/09/2025,17:41:32,"-75,573166","6,279467",0,2,0,55